#!/bin/bash

# if [[ !python manage_train.py --config_file models/$1/config.yaml ]] 
# then
#     echo "Model $1 training setup"
# else
#     echo "Model $1 config doesn't exist!"
# fi
echo "Training is configured as below:"
cat models/$1/config.yaml

read -p "Are you sure?[y/n] " -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]];
then

if [ -z "$1" ]
  then
    echo "No argument supplied"
    exit 1
fi

if [ $2 = "local" ]; then
    echo "Inferring locally"
    python infer_model.py --model_name=$1
else
    echo "Inferring with sbatch GPU"
    model_name=$1
    export model_name
    echo "Inferring with "$model_name
    bash sbatch_infer.sh --export=model_name 
fi

else
    echo "Inference aborted"
fi