#!/bin/bash

# if [[ !python manage_train.py --config_file models/$1/config.yaml ]] 
# then
#     echo "Model $1 training setup"
# else
#     echo "Model $1 config doesn't exist!"
# fi
for ARGUMENT in "$@"
do

    KEY=$(echo $ARGUMENT | cut -f1 -d=)
    VALUE=$(echo $ARGUMENT | cut -f2 -d=)   

    case "$KEY" in
            config)              config=${VALUE} ;;
            *)   
    esac    
done
echo config=$config

if [ -z "$1" ]
  then
    echo "No argument supplied"
    exit 1
fi

echo "Training is configured as below:"
cat models/$1/config.yaml

read -p "Are you sure?[y/n] " -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]];
then

if [ $2 = "local" ]; then
    echo "Training locally"
    python train_model.py --model_name=$1
else
    echo "Training with sbatch GPU"
    model_name=$1
    export model_name
    echo "Training "$model_name
    sbatch --export=model_name sbatch_train.sh 
fi


else 
    echo "Training aborted"
fi


